### ISSUE TITLE
Edictor url not found

### ISSUE THREAD

**Issue by FredericBlum** [lexibank/baf2#15]
@LinguList When running the `cldfbench download lexibank_baf2.py` command, I receive the following error message:

```shell
(lb) blum@lingn45w baf2 % cldfbench download lexibank_baf2.py
INFO    running _cmd_download on baf2 ...
Traceback (most recent call last):
  File "/Users/blum/Projects/datasets/venv/lb/bin/cldfbench", line 8, in <module>
    sys.exit(main())
  File "/Users/blum/Projects/datasets/venv/lb/lib/python3.9/site-packages/cldfbench/__main__.py", line 89, in main
    return args.main(args) or 0
  File "/Users/blum/Projects/datasets/venv/lb/lib/python3.9/site-packages/cldfbench/commands/download.py", line 12, in run
    with_dataset(args, 'download')
  File "/Users/blum/Projects/datasets/venv/lb/lib/python3.9/site-packages/cldfbench/cli_util.py", line 161, in with_dataset
    res = func(*arg, args)
  File "/Users/blum/Projects/datasets/venv/lb/lib/python3.9/site-packages/cldfbench/dataset.py", line 157, in _cmd_download
    self.cmd_download(args)
  File "/Users/blum/Projects/datasets/baf2/./lexibank_baf2.py", line 39, in cmd_download
    data = fetch(
  File "/Users/blum/Projects/datasets/venv/lb/lib/python3.9/site-packages/pyedictor/util.py", line 29, in fetch
    data = urlopen(url).read()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

What is the current edictor-link to integrate the download? Currently chosen is `https://digling.org/edictor/bangime`.

**Comment by LinguList** [comment]
Sorry, as I moved `digling.org`, the replacement link is now `https://lingulist.de/digling/edictor/`,so it would be

https://lingulist.de/digling/edictor/?file=bangime&remote_dbase=bangime

for the data and

```python
base_url="https://lingulist.de/digling.org/edictor",
```
